---
- hosts: localhost
  connection: local
  vars:
    project_limits_memory: 2Gi
    git_repo: "ssh://git@192.168.1.55:10022/liveaverage/ocp-project-quota.git"
    # git_keyfile in vault.yml
    ocp_api_url: "https://g1.gxr.me:8443"
    # ocp_api_token in vault.yml
    ocp_project_name: "project-test"
    ocp_project_name_display: "This is a Test"
    ocp_project_requester: "project-user"
    ocp_project_description: "Provisioned by Ansible"
    ocp_project_admin_users: test2,tester,developer,administrator
  roles:
    - project-bootstrap  
